### PR TITLE
fix: AtrributeError

### PR DESCRIPTION
**Pull request by laszlokr**

### CODE REVIEW

**Comment by janikvonrotz** [comment]
@laszlokr The solution in this case is that we no longer use this module. It is also mentioned in the Wiki: https://www.odoo-wiki.org/sale-order-contact-person.html#sale-order-contact-person

**Comment by janikvonrotz** [comment]
@laszlokr Can you create a PR to remove this module?

**Comment by janikvonrotz** [comment]
It should not have been migrated in the first place.

**Comment by laszlokr** [comment]
> @laszlokr Can you create a PR to remove this module?

@janikvonrotz  I removed the migration branch, created another one and opened a new PR

**Pull request closed without merging**
